version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fastapi_postgres_db
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend_service
    ports:
      - "8005:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=fastapi_db
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

volumes:
  fastapi_postgres_data:
