version: '3.8'

services:
  db:
    image: postgres:15
    container_name: registration_db_v2
    environment:
      POSTGRES_DB: registration_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - reg_postgres_data_v2:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask_backend_v2
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=registration_db
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend_v2
    ports:
      - "5174:5173"
    depends_on:
      - backend

volumes:
  reg_postgres_data_v2:
